joint_limits:
  joint_one:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57

  joint_two:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    min_position: -1.307
    max_position: 0.617

  joint_three:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57

  joint_four:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57

  joint_five:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57

  joint_six:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.5
    has_position_limits: true
    min_position: -1.221
    max_position: 0.097

  joint_seven:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.5
    has_position_limits: true
    min_position: -1.221
    max_position: 0.097
