# controller_manager:
#   ros__parameters:
#     update_rate: 100
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
#     arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController
#     gripper_controller:
#       type: joint_trajectory_controller/JointTrajectoryController

# arm_controller:
#   ros__parameters:
#     joints:
#       - joint_one
#       - joint_two
#       - joint_three
#       - joint_four
#       - joint_five
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     allow_nonzero_velocity_at_trajectory_end: true

# gripper_controller:
#   ros__parameters:
#     joints:
#       - joint_six
#       - joint_seven
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#     allow_nonzero_velocity_at_trajectory_end: true








controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    # Comment out or remove gripper_controller if not needed for now
    # gripper_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint_one
      - joint_two
      - joint_three
      - joint_four
      - joint_five
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

# Remove or comment out this whole section if you don’t want gripper now
# gripper_controller:
#   ros__parameters:
#     joints:
#       - joint_six
#       - joint_seven
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#     allow_nonzero_velocity_at_trajectory_end: true
