ros2 action send_goal /move_action moveit_msgs/action/MoveGroup -f - <<EOF
request:
  group_name: "arm"
  goal_constraints:
  - position_constraints:
    - header:
        frame_id: "world"
      link_name: "tool0"
      constraint_region:
        primitive_poses:
        - position:
            x: 0.4
            y: 0.1
            z: 0.3
          orientation:
            x: 0.0
            y: 0.0
            z: 0.0
            w: 1.0
        primitives:
        - type: 1
          dimensions: [0.001, 0.001, 0.001]
    orientation_constraints:
    - header:
        frame_id: "world"
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
      link_name: "wrist_link"
      absolute_x_axis_tolerance: 0.01
      absolute_y_axis_tolerance: 0.01
      absolute_z_axis_tolerance: 0.01
      weight: 1.0
  allowed_planning_time: 5.0
EOF
