# Default initial positions for robotic_arm's ros2_control fake system

initial_positions:
  elbow_joint: 0
  forearm_joint: 0
  gripper_right_joint: 0
  rotating_base_joint: 0
  shoulder_joint: 0
  wrist_joint: 0