# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm:
  ros__parameters:
    joints:
      - rotating_base_joint
      - shoulder_joint
      - elbow_joint
      - forearm_joint
      - wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
gripper:
  ros__parameters:
    joint: gripper_right_joint