arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 10
  kinematics_solver_timeout: 0.2
  kinematics_solver_search_resolution: 0.005
  position_only_ik: true
  tip_link: ik_frame   # Must be here and match your URDF tip






# arm:
#   kinematics_solver: trac_ik_kinematics_plugin/TracIKPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   position_only: true
#   # TracIK allows some flexibility with partial constraints
