arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 10              # More retries
  kinematics_solver_timeout: 0.2              # Increase timeout for better chance of success
  kinematics_solver_search_resolution: 0.005  # Keep this as is
  position_only_ik: true                      # (Optional) if orientation isn't critical
