# moveit_controller_manager: "moveit_ros_control_interface/Ros2ControlManager"

# controller_names:
#   - arm_controller
#   - gripper_controller

# arm_controller:
#   type: FollowJointTrajectory
#   joints:
#     - joint_one
#     - joint_two
#     - joint_three
#     - joint_four
#     - joint_five
#   action_ns: /arm_controller/follow_joint_trajectory
#   default: true

# gripper_controller:
#   type: FollowJointTrajectory
#   joints:
#     - joint_six
#     - joint_seven
#   action_ns: /gripper_controller/follow_joint_trajectory
#   default: false



# # moveit_controller_manager: "moveit_simple_controller_manager/MoveItSimpleControllerManager"











moveit_controller_manager: "moveit_ros_control_interface/Ros2ControlManager"

controller_names:
  - arm_controller

arm_controller:
  type: FollowJointTrajectory
  joints:
    - joint_one
    - joint_two
    - joint_three
    - joint_four
    - joint_five
  action_ns: /arm_controller/follow_joint_trajectory
  default: true
