# # MoveIt uses this configuration for controller management

# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
#   controller_names:
#     - arm_controller
#     - gripper_controller

#   arm_controller:
#     type: FollowJointTrajectory
#     joints:
#       - joint_one
#       - joint_two
#       - joint_three
#       - joint_four
#       - joint_five
#     action_ns: follow_joint_trajectory
#     default: true  
#   gripper_controller:
#     type: GripperCommand
#     joints:
#       - joint_seven
#       - joint_six
#     action_ns: gripper_cmd
#     default: true


moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller
  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_one
      - joint_two
      - joint_three
      - joint_four
      - joint_five
  gripper_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - joint_six
      - joint_seven