planning_pipelines:
  arm:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters: >
      default_planner_request_adapters/ResolveConstraintFrames
      default_planner_request_adapters/ValidateWorkspaceBounds
      default_planner_request_adapters/CheckStartStateBounds
      default_planner_request_adapters/CheckStartStateCollision
      default_planner_request_adapters/AddTimeParameterization
    response_adapters:
      - default_planner_response_adapters/AddTimeOptimalParameterization
      - default_planner_response_adapters/ValidateSolution
      - default_planner_response_adapters/DisplayMotionPath
