moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - arm
    - gripper
  arm:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rotating_base_joint
      - shoulder_joint
      - elbow_joint
      - forearm_joint
      - wrist_joint
  gripper:
    action_ns: forward_command
    type: ForwardCommand
    default: true
    joints:
      - gripper_right_joint