default_planning_pipeline: ompl

planning_pipelines:
  ompl:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters: >
      default_planner_request_adapters/ResolveConstraintFrames
      default_planner_request_adapters/AddTimeParameterization
      default_planner_request_adapters/ValidateWorkspaceBounds
    start_state_max_bounds_error: 0.1
    planner_configs:
      RRTConnect:
        type: geometric::RRTConnect
        range: 0.0
      RRTstar:
        type: geometric::RRTstar
        range: 0.0
