planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.05
    planner_attempts: 20
    longest_valid_segment_fraction: 0.005
  RRTstar:
    type: geometric::RRTstar
    range: 0.05
    planner_attempts: 20
    longest_valid_segment_fraction: 0.005
arm:
  planner_configs: [RRTConnect, RRTstar]
  default_planner: RRTConnect
  projection_evaluator: joints(rotating_base_joint,shoulder_joint)
  longest_valid_segment_fraction: 0.005

