robot_description_planning:
  cartesian_limits:
    max_trans_vel: 1.0
    max_trans_acc: 2.25
    max_trans_dec: -5.0
    max_rot_vel: 1.57
    max_rot_acc: 3.5
    max_rot_dec: -5.0
  joint_limits:
    rotating_base_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 1.0
    shoulder_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 1.0
    elbow_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 1.0
    forearm_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true  
      max_acceleration: 1.0
    wrist_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 1.0
    gripper_right_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 1.0