# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     arm:
#       type: joint_trajectory_controller/JointTrajectoryController

#     gripper:
#       type: forward_command_controller/ForwardCommandController  # more appropriate for simple grippers

# arm:
#   ros__parameters:
#     joints:
#       - rotating_base_joint
#       - shoulder_joint
#       - elbow_joint
#       - forearm_joint
#       - wrist_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     state_publish_rate: 50.0  # Optional — adjust as needed
#     action_monitor_rate: 20.0 # Optional — adjust for trajectory action server
#     allow_partial_joints_goal: false

# gripper:
#   ros__parameters:
#     joints:
#       - gripper_right_joint
#     interface_name: position

# ros2_controllers.yaml - Fixed Configuration

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper:
      type: forward_command_controller/ForwardCommandController  # Suitable for simple grippers

arm:
  ros__parameters:
    joints:
      - rotating_base_joint
      - shoulder_joint
      - elbow_joint
      - forearm_joint
      - wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0       # Optional — adjust as needed
    action_monitor_rate: 20.0      # Optional — adjust for trajectory action server
    allow_partial_joints_goal: false

gripper:
  ros__parameters:
    joints:
      - gripper_right_joint
    interface_name: position       # Correct for ForwardCommandController
