# # This config file is used by ros2_control
# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Hz

#     arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController


#     gripper_controller:
#       type: position_controllers/GripperActionController


#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# arm_controller:
#   ros__parameters:
#     joints:
#       - joint_one
#       - joint_two
#       - joint_three
#       - joint_four
#       - joint_five
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     allow_nonzero_velocity_at_trajectory_end: true
# gripper_controller:
#   ros__parameters:
#     joint: 
#       - joint_seven
      


controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters: {}

arm_controller:
  ros__parameters:
    joints:
      - joint_one
      - joint_two
      - joint_three
      - joint_four
      - joint_five
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

gripper_controller:
  ros__parameters:
    joints:
      - joint_six
      - joint_seven
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true
